# Generated by Django 5.x
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='WaitlistSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('stack', models.CharField(blank=True, max_length=160)),
                ('monthly_sessions', models.IntegerField(blank=True, null=True)),
                ('biggest_pain', models.TextField(blank=True)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_label', models.CharField(blank=True, max_length=20)),
                ('revenue_risk', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='landing', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
